version: '3.8'

services:
  development:
    image: postgis/postgis:13-3.1
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: qikChallenge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
